import { Item } from './types';

export const CATEGORIES = [
  "All",
  "Rice & Grains",
  "Flours",
  "Dals & Pulses",
  "Spices & Masalas",
  "Oils & Ghee",
  "Dry Fruits & Seeds",
  "Dairy & Breakfast",
  "Household & Cleaning",
  "Personal Care"
];

// Comprehensive list of Chennai areas for location filtering
export const CHENNAI_AREAS = [
  "Adyar", "Alandur", "Alwarpet", "Ambattur", "Anna Nagar", "Arumbakkam", "Ashok Nagar", 
  "Avadi", "Ayanavaram", "Besant Nagar", "Chromepet", "Chetpet", "Choolaimedu", 
  "East Coast Road (ECR)", "Egmore", "Ekkaduthangal", "Ennore", "Gopalapuram", 
  "Guindy", "IIT Madras", "Injambakkam", "K.K. Nagar", "Keelkattalai", 
  "Kilpauk", "Kodambakkam", "Kolathur", "Korattur", "Kottivakkam", "Kotturpuram", 
  "Koyambedu", "Kundrathur", "Madipakkam", "Madhavaram", "Manapakkam", "Mandaveli", 
  "Medavakkam", "Meenambakkam", "Mylapore", "Nandanam", "Nanganallur", 
  "Neelankarai", "Nungambakkam", "Old Mahabalipuram Road (OMR)", "Otteri", 
  "Padi", "Pallavaram", "Pallikaranai", "Pammal", "Park Town", "Parrys", 
  "Perambur", "Perungudi", "Poonamallee", "Porur", "Purasaiwalkam", 
  "Ramapuram", "Red Hills", "Royapettah", "Royapuram", "Saidapet", 
  "Saligramam", "Santhome", "Selaiyur", "Shenoy Nagar", "Sholinganallur", 
  "Sowcarpet", "St. Thomas Mount", "T. Nagar", "Tambaram", "Teynampet", 
  "Tharamani", "Thiruvanmiyur", "Thiruvottiyur", "Thoraipakkam", "Tirulus", 
  "Tondiarpet", "Triplicane", "Vadapalani", "Valasaravakkam", "Velachery", 
  "Vepery", "Villivakkam", "Virugambakkam", "Washermanpet", "West Mambalam"
].sort();

// Seeded list based on the user's provided list
const RAW_ITEMS = [
  { name: "Turmeric Powder", category: "Spices & Masalas" },
  { name: "Sugar", category: "Dairy & Breakfast" },
  { name: "Jaggery", category: "Dairy & Breakfast" },
  
  // Rice & Grains
  { name: "Idli Rice / Boiled Rice / Salem Rice", category: "Rice & Grains" },
  { name: "Steamed / Raw / Sona Masoori Rice", category: "Rice & Grains" },
  { name: "High Quality Raw Rice (Pongal)", category: "Rice & Grains" },
  { name: "Dosa Rice", category: "Rice & Grains" },
  { name: "Basmati Rice", category: "Rice & Grains" },
  { name: "Organic Rice Varieties", category: "Rice & Grains" },
  { name: "Millets Varieties", category: "Rice & Grains" },
  { name: "Oats", category: "Rice & Grains" },
  { name: "Brown Rice", category: "Rice & Grains" },
  { name: "Poha (Thick or Thin)", category: "Rice & Grains" },
  { name: "Vermicelli", category: "Rice & Grains" },
  { name: "Instant Rice Sevai", category: "Rice & Grains" },
  { name: "Sago / Javvarisi", category: "Rice & Grains" },

  // Flours
  { name: "Wheat Flour", category: "Flours" },
  { name: "Maida", category: "Flours" },
  { name: "Ragi Flour", category: "Flours" },
  { name: "Idiyappam Flour", category: "Flours" },
  { name: "Rice Flour", category: "Flours" },
  { name: "Besan Flour", category: "Flours" },
  { name: "Bansi Rava / Wheat Rava", category: "Flours" },
  { name: "Rava / Chiroti Rava", category: "Flours" },

  // Dals & Pulses
  { name: "Toor Dal", category: "Dals & Pulses" },
  { name: "Round Urad Dal", category: "Dals & Pulses" },
  { name: "Yellow Moong Dal", category: "Dals & Pulses" },
  { name: "Chana Dal", category: "Dals & Pulses" },
  { name: "Split Urad Dal", category: "Dals & Pulses" },
  { name: "Rajma / Peas / Green Gram", category: "Dals & Pulses" },
  { name: "Fried Gram Dal", category: "Dals & Pulses" },
  { name: "Horsegram & Flaxseeds", category: "Dals & Pulses" },
  { name: "Peanuts", category: "Dals & Pulses" },

  // Spices & Masalas (Group 1)
  { name: "Tamarind", category: "Spices & Masalas" },
  { name: "Red Chilli", category: "Spices & Masalas" },
  { name: "Crystal Salt", category: "Spices & Masalas" },
  { name: "Powder Salt", category: "Spices & Masalas" },
  { name: "Red Chilli Powder", category: "Spices & Masalas" },
  { name: "Dhania Powder", category: "Spices & Masalas" },
  { name: "Pepper Powder", category: "Spices & Masalas" },
  { name: "Cumin Powder", category: "Spices & Masalas" },
  { name: "Amchoor Powder", category: "Spices & Masalas" },
  { name: "Garam Masala Powder", category: "Spices & Masalas" },
  { name: "Chat Masala Powder", category: "Spices & Masalas" },
  { name: "Biryani Masala / Curry Masala", category: "Spices & Masalas" },
  { name: "Sambar / Rasam / Vathakulambu Powder", category: "Spices & Masalas" },
  { name: "Idli Powder", category: "Spices & Masalas" },
  { name: "Readymade Powders", category: "Spices & Masalas" },
  { name: "ENO Fruit Salt", category: "Spices & Masalas" },
  { name: "Cooking / Baking Soda", category: "Spices & Masalas" },
  { name: "Baking Powder", category: "Spices & Masalas" },
  { name: "Yeast", category: "Spices & Masalas" },

  // Oils & Ghee
  { name: "Cooking Oil", category: "Oils & Ghee" },
  { name: "Gingely Oil", category: "Oils & Ghee" },
  { name: "Coconut Oil", category: "Oils & Ghee" },
  { name: "Ghee or Butter", category: "Oils & Ghee" },
  { name: "Olive Oil / Other Oils", category: "Oils & Ghee" },
  { name: "Deepam Oil", category: "Oils & Ghee" },

  // Spices & Masalas (Group 2)
  { name: "Mustard Seeds", category: "Spices & Masalas" },
  { name: "Pepper", category: "Spices & Masalas" },
  { name: "Cumin Seeds", category: "Spices & Masalas" },
  { name: "Fenugreek Seeds", category: "Spices & Masalas" },
  { name: "Poppy Seeds", category: "Spices & Masalas" },
  { name: "Coriander Seeds", category: "Spices & Masalas" },
  { name: "Fennel Seeds", category: "Spices & Masalas" },
  { name: "Dry Ginger", category: "Spices & Masalas" },
  { name: "Sesame Seeds", category: "Spices & Masalas" },
  { name: "Ajwain", category: "Spices & Masalas" },
  { name: "Hing", category: "Spices & Masalas" },
  { name: "Cardamom", category: "Spices & Masalas" },
  { name: "Cinnamon", category: "Spices & Masalas" },
  { name: "Cloves", category: "Spices & Masalas" },
  { name: "Kalpasi / Stone Flower", category: "Spices & Masalas" },
  { name: "Biryani Spices Packet", category: "Spices & Masalas" },
  { name: "Vanilla Essence", category: "Spices & Masalas" },
  { name: "Saffron", category: "Spices & Masalas" },

  // Dry Fruits
  { name: "Cashews", category: "Dry Fruits & Seeds" },
  { name: "Badam", category: "Dry Fruits & Seeds" },
  { name: "Dates", category: "Dry Fruits & Seeds" },
  { name: "Rock Candy / Dry Grapes", category: "Dry Fruits & Seeds" },

  // Dairy & Breakfast
  { name: "Instant Coffee Powder", category: "Dairy & Breakfast" },
  { name: "Tea Powder", category: "Dairy & Breakfast" },
  { name: "Papad", category: "Dairy & Breakfast" },
  { name: "Cocoa Powder", category: "Dairy & Breakfast" },
  { name: "Health Drinks", category: "Dairy & Breakfast" },
  { name: "Noodles", category: "Dairy & Breakfast" },
  { name: "Pasta", category: "Dairy & Breakfast" },
  { name: "Macaroni", category: "Dairy & Breakfast" },
  { name: "Sphagetti", category: "Dairy & Breakfast" },
  { name: "Ketchup / Jam", category: "Dairy & Breakfast" },
  { name: "Organic Honey", category: "Dairy & Breakfast" },
  { name: "Bread Packet", category: "Dairy & Breakfast" },
  { name: "Paneer", category: "Dairy & Breakfast" },
  { name: "Cheese Slices", category: "Dairy & Breakfast" },
  { name: "Butter", category: "Dairy & Breakfast" },
  { name: "Idli Dosa Batter", category: "Dairy & Breakfast" },
  { name: "Fresh Cream", category: "Dairy & Breakfast" },
  { name: "Snacks", category: "Dairy & Breakfast" },

  // Personal Care
  { name: "Toothpaste", category: "Personal Care" },
  { name: "Toothbrush", category: "Personal Care" },
  { name: "Bathing Soap", category: "Personal Care" },
  { name: "Shampoo", category: "Personal Care" },
  { name: "Face Powder", category: "Personal Care" },
  { name: "Hand Sanitizer", category: "Personal Care" },
  { name: "Deodorant", category: "Personal Care" },
  { name: "Body Lotion", category: "Personal Care" },
  { name: "Kajal / Kum Kum", category: "Personal Care" },
  { name: "Shaving Lotion", category: "Personal Care" },
  { name: "Shaving Cream", category: "Personal Care" },
  { name: "Hair Gel", category: "Personal Care" },
  { name: "Razor Blades", category: "Personal Care" },
  { name: "Baby Products", category: "Personal Care" },
  { name: "Sanitary Pads", category: "Personal Care" },
  { name: "Medicines / Bandages", category: "Personal Care" },

  // Household & Cleaning
  { name: "Dish Washing Soaps", category: "Household & Cleaning" },
  { name: "Dish Washing Powder", category: "Household & Cleaning" },
  { name: "Washing Powder", category: "Household & Cleaning" },
  { name: "Washing Soaps", category: "Household & Cleaning" },
  { name: "Toilet Cleaner", category: "Household & Cleaning" },
  { name: "Floor Cleaner", category: "Household & Cleaning" },
  { name: "Kitchen Cleaner", category: "Household & Cleaning" },
  { name: "Toilet Paper", category: "Household & Cleaning" },
  { name: "Kitchen Tissue", category: "Household & Cleaning" },
  { name: "Garbage Bags", category: "Household & Cleaning" },
  { name: "Car Cleaner", category: "Household & Cleaning" },
  { name: "Dettol", category: "Household & Cleaning" },
  { name: "Mosquito Liquid", category: "Household & Cleaning" },
  { name: "Odonil", category: "Household & Cleaning" },
  { name: "Napthalene Balls", category: "Household & Cleaning" },
  { name: "Match Box", category: "Household & Cleaning" },
  { name: "Deepa Oil (Puja)", category: "Household & Cleaning" },
  { name: "Cotton Thread", category: "Household & Cleaning" },
  { name: "Camphor", category: "Household & Cleaning" },
  { name: "Incense Sticks", category: "Household & Cleaning" },
  { name: "Dhoop", category: "Household & Cleaning" },
  { name: "Light Bulbs", category: "Household & Cleaning" },
  { name: "Batteries", category: "Household & Cleaning" },
  { name: "Candles", category: "Household & Cleaning" },
];

export const GROCERY_ITEMS: Item[] = RAW_ITEMS.map((item, index) => ({
  id: `item-${index}`,
  name: item.name,
  category: item.category,
  imageSeed: 100 + index
}));